version: "3.9"

services:
  mesh-cleaner:
    container_name: mesh-cleaner-service
    build:
      context: ./mesh-cleaner-service
    volumes:
      - ./mesh-cleaner-service/meshes:/app/meshes
    working_dir: /app
    command: python main.py

  mesh-cleaner-api:
    container_name: mesh-cleaner-api
    build:
      context: ./mesh-cleaner-api
    ports:
      - "8000:8000"
    volumes:
      - ./mesh-cleaner-service/meshes:/app/meshes
      - ./mesh-cleaner-service:/mesh-cleaner-service

  mesh-cleaner-frontend:
    container_name: mesh-cleaner-fe
    build:
      context: ./mesh-cleaner-fe
    ports:
      - "3000:80"
