version: "3.9"

services:
  mesh-cleaner-service:
    container_name: mesh-cleaner-service
    build:
      context: ./mesh-cleaner-service
    ports:
      - "8000:8000"
    volumes:
      - ./mesh-cleaner-service/meshes:/app/meshes
      - ./mesh-cleaner-service:/mesh-cleaner-service

  mesh-cleaner-frontend:
    container_name: mesh-cleaner-fe
    build:
      context: ./mesh-cleaner-fe
    ports:
      - "3000:80"
